version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - backend-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth-service
    networks:
      - backend-network

  auth-service:
    image: nureternovyidaniil/pidrobitok-auth-service:latest
    ports:
      - "8082:8080"
      - "8083:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_DATABASE=${AUTH_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_TOKEN_LIFETIME=${JWT_TOKEN_LIFETIME}
    depends_on:
      - sql-server
    networks:
      - backend-network

  job-service:
    image: andriilavrovnure/pidrobitok-job-service:latest
    ports:
      - "8084:8080"
      - "8085:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SQL_SERVER=${SQL_SERVER}
      - SQL_DATABASE=${JOB_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_TOKEN_LIFETIME=${JWT_TOKEN_LIFETIME}
    depends_on:
      - sql-server
    networks:
      - backend-network

  frontend:
    image: yaroff/pidrobitok-front:latest
    ports:
      - "3000:5173"
    depends_on:
      - auth-service
      - job-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  sqldata:
